// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntxgjxrratuiohtyiuww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50eGdqeHJyYXR1aW9odHlpdXd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NzQ0ODcsImV4cCI6MjA3MjE1MDQ4N30.WulpcrLzsiIq6lg2yWHNBuERvSEhPQz-Vs6323MVBXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});